version: "3.8"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "bash", "-c", "unset" , "JMX_PORT" ,";" ,"kafka-topics.sh","--zookeeper","zookeeper:2181","--list"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  kafka:
    image: docker.io/bitnami/kafka:3.8
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://0.0.0.0:9093,EXTERNAL://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9093,EXTERNAL://localhost:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CREATE_TOPICS="db-monitoring:1:1,query-monitoring:1:1"
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list"]
      interval: 10s
      retries: 5
      
    restart: always
    networks:
      - app_network

  pg_activity:
    image: tophfr/pg_activity:${TAG}
    build:
      context: pg_activity
      dockerfile: Dockerfile
      args:
        PG_ACTIVITY_VERSION: ${VERSION}
    environment:
      PGHOST: postgresql_db
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: postgres
    volumes:
      - "Pg_activity_Data:/app/ProducerConsumer/Pg_activity_Data"
    networks:
      - app_network
    

  stress_tester:
    build:
      context: ProducerConsumer/ActivityWatcher
    depends_on:
      postgresql_db:
        condition: service_healthy
    environment:
      HOST: postgresql_db
      PORT: 5432
      USER: postgres
      DBNAME: postgres
      CONNECTIONS: 50
      DURATION: 100
      DELETE_CONNECTIONS: 1
      DELETE_DURATION: 1
      PGPASSWORD: postgres
    logging:
      driver: none
    restart: always
    networks:
      - app_network

  postgresql_db:
    image: docker.io/bitnami/postgresql:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRESQL_MAX_CONNECTIONS=1000
      
    ports:
      - "5432:5432"
    volumes:
      - "postgresql_data:/bitnami"
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    

  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - "Pg_activity_Data:/app/ProducerConsumer/Pg_activity_Data"
    depends_on:
      kafka:
        condition: service_healthy
      postgresql_db:
        condition: service_healthy
      pg_activity:
        condition: service_started
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9093
      - KAFKA_TOPIC=events
      - POSTGRESQL_HOST=postgresql_db
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DB=postgres
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  postgresql_data:
    driver: local
  Pg_activity_Data:
    driver: local

  
